### ISSUE TITLE
Level Architecture

### ISSUE THREAD

**Issue by emdok** [ChrisKurz098/NASAteroids#15]
We need to spend some time thinking about how each level gets harder. 

Do we create a function that randomizes how many asteroids and their size appear based on the level and difficulty.

**Comment by ChrisKurz098** [comment]
So we are not doing levels anymore. The plan is this: 

- We just keep making more Asteroids every 30sec-1min. If they can't destroy enough asteroid fast enough, they will have no more room and inevitably get hit.

- Perhaps the time between adding asteroids gets slightly shorter each time

- Then we have just one game over screen where all the exp and points are calculated
